default: &default
  adapter: postgresql
  encoding: unicode
  host: 'localhost'
  pool: 5
  username: 'sirdembo_user'
  password: 'secret'

development:
  <<: *default
  database: sirdembo

test:
  <<: *default
  database: sirdembo

production:
  <<: *default
  database: sirdembo