default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: 'sirdembo_user'
  password: 'secret'

development:
  <<: *default
  database: sirdembo
  host: 'localhost'

test:
  <<: *default
  database: sirdembo
  host: 'localhost'

production:
  <<: *default
  database: sirdembo